[[module.imports]]
path = "github.com/hugomods/twikoo"

[[module.imports]]
path = "github.com/hbstack/docs"

[params.hugopress.modules.hb-docs-comments-twikoo.hooks.hb-docs-doc-comments]

[params.hugopress.modules.hb-docs-comments-twikoo.hooks.body-end]
