[[module.imports]]
path = "github.com/hbstack/giscus"

[[module.imports]]
path = "github.com/hbstack/docs"

[params.hugopress.modules.hb-docs-comments-giscus.hooks.hb-docs-doc-comments]

[params.hugopress.modules.hb-docs-comments-giscus.hooks.body-end]
