[[module.imports]]
path = "github.com/hbstack/docs"

[[module.imports]]
path = "github.com/hbstack/blog/modules/featured-image"

[params.hugopress.modules.hb-docs-doc-featured-image.hooks.hb-docs-doc-content-begin]
